### ISSUE TITLE
Error when tried to run script

### ISSUE THREAD

**Issue by sinankizar** [pokertour/Cloudflare-Grafana#1]
Hello,

First off, thank you for the effort you put in this.

I had to create the file with dudo added at the beginning. After succesfully created the file when it comes to make the script executable there is no output. After that i tried tı run the script:

mat@MAT-TR-MNTR:~$ ./cloudflare-analytics.sh
jq: error (at <stdin>:1): Cannot iterate over null (null)
mat@MAT-TR-MNTR:~$

What might be wrong?

Thanks in advance.

**Comment by pokertour** [comment]
Hello,

What do you mean by dudo added at the beginning ?
Did you setup an APIkey or a token in cloudflare ?
Did you give enough access right to this token/key ?

The cloudflarezoneid is correct ?

**Comment by sinankizar** [comment]
Sorry for typo,
I mean sudo
And yes I have setup apikey and tokesn both on influx and cloudflare
ANd zoneid is correct

Btw when i run api test command which cloudflare gave me, it returns as success

Do I need to roll the API key from cloudflare?

**Comment by pokertour** [comment]
np

okay but are you running the script in TOKEN or APIKEY mode ? you can choose the mode line 29

what do you mean by rolling the apikey ?

**Comment by pokertour** [comment]
can you also try to run the script with sudo ?

**Comment by sinankizar** [comment]
I am running it in sudo mode also and getting same error. Mode is TOKEN and tried to change to APIKEY and get the same result.

# Endpoint URL for InfluxDB
InfluxDBURL="http://192.168.2.100" #Your InfluxDB Server, http://FQDN or https://FQDN if using SSL
InfluxDBPort="8086" #Default Port
InfluxBucket="cloudflare" #Default Database
InfluxOrg="My organization name"
InfluxToken="got it from influx"

# Endpoint URL for login action
cloudflareauthmethod="TOKEN" #Choose Authentication method. Either TOKEN (single token with specific rights) or APIKEY (Global API KEY with Email)
cloudflareapikey="created it on cloudflare with Read analytics and logs and not rolled"
cloudflarezone="got it from cloudflare domain name"
cloudflareemail="cloudflare login email"
cloudflareapitoken="got it from cloudflare Global API Key"

**Comment by pokertour** [comment]
When you are running in TOKEN mode you don't need cloudflareapikey and cloudflareemail. You only need your zone ID and your APITOKEN.

I recreate your problem on my server. The problem is your zone id OR you api token.

When you create the token on Cloudflare you can't setup has Global.
This is the one you want to configure : 
![image](https://github.com/pokertour/Cloudflare-Grafana/assets/7757451/e6f70593-7839-4458-b1de-28db9bac64c3)

Create it with Read analytics and logs template

**Comment by sinankizar** [comment]
Wow!
Now it's working. Thank you so much. Commented out email and apikey sections and recreated the api token solved the issue. 

Now another challenge:
How can I add multiple zones :D

**Comment by pokertour** [comment]
Great ! 

That's a really good question :D 

For the moment only by copying your script and creating another bucket Because inside Influx i'm not linking the value with a zone. I'll add that to my TODO list :)

**Comment by sinankizar** [comment]
That came to my mind too. Will try and share the results. Thank you so much again.

**Comment by pokertour** [comment]
Your welcome :)
Okay, don't hesitate to make PR :)
